### ISSUE TITLE
Making spin available

### ISSUE THREAD

**Issue by c00kiemon5ter** [fermyon/homebrew-tap#1]
hey hello there,

It would be great to have a tap with spin and properly install it through homebrew.
Are you moving forward with this?

In any case, thank you for your work and time!

**Comment by kate-goldenring** [comment]
Hi @c00kiemon5ter. Sorry for the delay here. We wanted to see if we could get Spin into `homebrew-core` but ended up closing https://github.com/Homebrew/homebrew-core/pull/133861, finding that they disallow the use of `rustup` in core formulas, which is required for Spin since Wasm targets are not added to Rust by default.

Anyways, working on adding this to our own tap here now. Should be coming soon

**Comment by kate-goldenring** [comment]
@c00kiemon5ter Spin is now available to install via Homebrew: `brew tap fermyon/tap && brew install fermyon/tap/spin`! 🎉

**Comment by c00kiemon5ter** [comment]
Thank you!
